sonar.projectKey=E-Sensia_echo-iframe_c7c3bfdd-e25a-4153-8b1e-7f1390eeac02
sonar.projectName=Next Frontend
sonar.sources=src,domain,services,config,utils,otel
sonar.tests=services,domain
sonar.test.inclusions=**/*.test.ts
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts
