sonar.projectKey=next_frontend
sonar.projectName=Next Frontend
sonar.sources=src,domain,services,config,utils,otel
sonar.tests=services,domain
sonar.test.inclusions=**/*.test.ts
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts
